seleniumhub:
        image: selenium/hub       
        restart: always
        ports:
           - 4444:4444
firefoxnode: 
        image: selenium/node-firefox-debug
        restart: always
        ports:
           - 4577
        links:
           - seleniumhub:hub
chromenode:
        image: selenium/node-chrome-debug
        restart: always
        ports:
           - 4578
        links:
           - seleniumhub:hub
